ApplicationForm/Heriyanto/Controllers/ApplicationFormsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Heriyanto;

namespace Heriyanto.Controllers
{
    public class ApplicationFormsController : Controller
    {
        private applicant_dbEntities db = new applicant_dbEntities();

        // GET: ApplicationForms
        public ActionResult Index()
        {
            return View(db.ApplicationForms.ToList());
        }

        // GET: ApplicationForms/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationForm applicationForm = db.ApplicationForms.Find(id);
            if (applicationForm == null)
            {
                return HttpNotFound();
            }
            return View(applicationForm);
        }

        // GET: ApplicationForms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationForms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Mobile_Phone_Number,Alternative_Phone_Number,Email,Place_of_Birth,Date_of_Birth,Last_Education,Collage_University,Major,Position_Apply,Event,Career_Ceenter,Referral_Name,Referral_Mobile_Phone_Number,Referral_Email")] ApplicationForm applicationForm)
        {
            if (ModelState.IsValid)
            {
                db.ApplicationForms.Add(applicationForm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationForm);
        }

        // GET: ApplicationForms/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationForm applicationForm = db.ApplicationForms.Find(id);
            if (applicationForm == null)
            {
                return HttpNotFound();
            }
            return View(applicationForm);
        }

        // POST: ApplicationForms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,Mobile_Phone_Number,Alternative_Phone_Number,Email,Place_of_Birth,Date_of_Birth,Last_Education,Collage_University,Major,Position_Apply,Event,Career_Ceenter,Referral_Name,Referral_Mobile_Phone_Number,Referral_Email")] ApplicationForm applicationForm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationForm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationForm);
        }

        // GET: ApplicationForms/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationForm applicationForm = db.ApplicationForms.Find(id);
            if (applicationForm == null)
            {
                return HttpNotFound();
            }
            return View(applicationForm);
        }

        // POST: ApplicationForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationForm applicationForm = db.ApplicationForms.Find(id);
            db.ApplicationForms.Remove(applicationForm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApplicationForm/Heriyanto/Views/ApplicationForms/Create.cshtml
@model Heriyanto.ApplicationForm

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
  $( function() {
      $("#dp1").datepicker({
          dateFormat: 'yy-mm-dd',
          changeMonth: true,
          yearRange: '1950:2020',
          changeYear: true
          });
  });
</script>

<style>
    .ui-datepicker {
        position: relative;
        z-index: 10000 !important;
    }
</style>

<script type="text/javascript">
    document.getElementById("dp1").value = "";
</script>

<div class="modal-header blue" style="background-color:#000066;">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:#ffffff">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" style="color:#ffffff">Application Form</h4>
</div>

@using (Html.BeginForm("saveCreate", "ApplicationForms", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="modal-body" style="margin:auto">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Name *</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Email *</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Mobile Phone Number *</label>
                        @Html.EditorFor(model => model.Mobile_Phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Alternative Phone Number</label>
                        @Html.EditorFor(model => model.Alternative_Phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Place of Birth *</label>
                        @Html.EditorFor(model => model.Place_of_Birth, new { htmlAttributes = new { @class = "form-control", required = "" } })
                        @Html.ValidationMessageFor(model => model.Place_of_Birth, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Date of Birth *</label>
                        <div class="input-group">
                            @Html.EditorFor(model => model.Date_of_Birth, new { htmlAttributes = new { @class = "form-control", @id = "dp1", @readonly = "readonly" } })
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.Date_of_Birth, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label style="font-weight: 100">Collage / University *</label>
                        @Html.EditorFor(model => model.Last_Education, new { htmlAttributes = new { @class = "form-control", required = "" } })
                        @Html.ValidationMessageFor(model => model.Last_Education, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Collage University *</label>
                        @Html.EditorFor(model => model.Collage_University, new { htmlAttributes = new { @class = "form-control", required = "" } })
                        @Html.ValidationMessageFor(model => model.Collage_University, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label style="font-weight: 100">Major *</label>
                        @Html.EditorFor(model => model.Major, new { htmlAttributes = new { @class = "form-control", required = "" } })
                        @Html.ValidationMessageFor(model => model.Major, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label style="font-weight: 100">Position Apply *</label>
                        @Html.TextAreaFor(model => model.Position_Apply, new { @class = "form-control", required = "" })
                        @Html.ValidationMessageFor(model => model.Position_Apply, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label style="font-weight: 100">Source *</label>
                        @Html.TextAreaFor(model => model.Source, new { @class = "form-control", required = "" })
                        @Html.ValidationMessageFor(model => model.Source, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->

    </div>
    <div class="modal-footer justify-content-between">

    </div>
}

ApplicationForm/Heriyanto/Views/ApplicationForms/Delete.cshtml
@model Heriyanto.ApplicationForm

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationForm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Alternative_Phone_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alternative_Phone_Number)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplicationForm/Heriyanto/Views/ApplicationForms/Details.cshtml
@model Heriyanto.ApplicationForm

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<div class="modal-header" style="background:#F5F5F5">
    <div class="field">
        <div class="row">
            <div class="col-md-10">
                <h2 class="modal-title">Detail Proses</h2>
            </div>
        </div>
    </div>
</div>
<div class="modal-body">
    <div class="card-body">
        TEST
    </div>
</div>

ApplicationForm/Heriyanto/Views/ApplicationForms/Edit.cshtml
@model Heriyanto.ApplicationForm

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<div class="modal-header blue" style="background-color:#000066;  max-width: none;">
    <h4 class="modal-title" style="color:#ffffff">Edit Resource Project Form</h4>
</div>

@using (Html.BeginForm("SaveEdit", "ApplicationForms", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ApplicationForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        @Html.HiddenFor(model => model.Mobile_Phone_Number)

        <div class="modal-body" style="margin:auto;">
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.Alternative_Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Alternative_Phone_Number, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Alternative_Phone_Number, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.Email)

                @Html.HiddenFor(model => model.Place_of_Birth)

                @Html.HiddenFor(model => model.Date_of_Birth)

                @Html.HiddenFor(model => model.Last_Education)

                @Html.HiddenFor(model => model.Collage_University)

                @Html.HiddenFor(model => model.Major)

                @Html.HiddenFor(model => model.Position_Apply)

                @Html.HiddenFor(model => model.Event)

                @Html.HiddenFor(model => model.Career_Ceenter)

                @Html.HiddenFor(model => model.Referral_Name)

                @Html.HiddenFor(model => model.Referral_Mobile_Phone_Number)

                @Html.HiddenFor(model => model.Referral_Email)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

ApplicationForm/Heriyanto/Views/ApplicationForms/Index.cshtml
@model IEnumerable<Heriyanto.ApplicationForm>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    function detailModal(url) {
        $('#modelContent').load(url);
        $('#myModal').modal('show');
    }

    function editModal(url) {
        $('#Edit').load(url);
        $('#myModalEdit').modal('show');
    }

    function deleteModal(url) {
        $('#Delete').load(url);
        $('#myModalDelete').modal('show');
    }
</script>

@using (Html.BeginForm("Index", "ApplicationForms", FormMethod.Get, new { id = "form1" }))
{
    <div class="row" id="ApplicationForm">
        <div class="col-lg-10" style="padding: 25px 0px">
            <div class="col-lg-3">
                @Html.TextBox("searchName", "", new { @class = "form-control", placeholder = "Name", id = "searchName", title = "Inputkan Nama", Value = ViewBag.CurrentFilter })
            </div>

            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModelCreate">
                <i class="glyphicon glyphicon-plus-sign">
                </i>
            </button>
        </div>
    </div>
}


<table class="table table-striped" id="listData">
    <thead style="border-top:3px solid #000066;">
        <tr>
            <th>
                <b>NAME</b>
            </th>
            <th>
                <b>EMAIL</b>
            </th>
            <th>
                <b>PHONE NUMBER</b>
            </th>
            <th>
                <b style="padding-left: 40px;">#</b>
            </th>
        </tr>
    </thead>
    <tbody style="background-color:#DDD6FF;border-top:3px solid #000066;">
        @foreach (var item in Model)
        {
            <tr style="border-top:1px solid #000066;">
                <td style="padding-top:15px;">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td style="padding-top:15px;">
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td style="padding-top:15px; color:#000066;">
                    @Html.DisplayFor(modelItem => item.Mobile_Phone_Number)
                </td>

                <td class="dropdown">
                    <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" style="color:white; background-color : #000066" aria-haspopup="true" aria-expanded="false">
                        MORE <span class="caret" style="margin-left: 5px; margin-top: 8px;"></span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="margin-top:-7px; margin-left:7px">
                        <ul class="dropdown-item" onclick="detailModal('@Url.Action("Details", "ApplicationForms", new { id = item.Name })')">Detail</ul>
                        <ul class="dropdown-item" onclick="editModal('@Url.Action("Edit", "ApplicationForms", new { id = item.Name })')">Ubah</ul>
                        <ul class="dropdown-item" onclick="deleteModal('@Url.Action("Delete", "ApplicationForms", new { id = item.Name })')">Hapus</ul>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <h3>@ViewBag.message</h3>
</div>

<div id='myModelCreate' class='modal fade'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='Create'>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" aria-labelledby="myModalLabel" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content" id="modelContent">
        </div>
    </div>
</div>

<div id='myModalEdit' class='modal fade'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='Edit'>
            </div>
        </div>
    </div>
</div>

<div id='myModalDelete' class='modal fade'>
    <div class="modal-dialog " style="max-width:400px">
        <div class="modal-content">
            <div id='Delete'>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


<script>
    var TeamDetailPostBackURL = '/ApplicationForms/Details';
    $(function () {
        $(".anchorDetail").click(function () {
            debugger;
            var $buttonClicked = $(this);
            var id = $buttonClicked.attr('data-id');
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: TeamDetailPostBackURL,
                contentType: "application/json; charset=utf-8",
                data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#myModalContentDetail').html(data);
                    $('#myModalDetail').modal(options);
                    $('#myModalDetail').modal('show');

                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });

    });
</script>


<script>
    $('#Create').load('/ApplicationForms/Create');
</script>
}